server.port=8084
spring.application.name=notification-service

spring.datasource.url=jdbc:h2:mem:notificationdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

customer.service.url=http://localhost:8081
customer.service.path=/customer/
