server.port=8081
spring.application.name=customer-service

spring.datasource.url=jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

product.service.url=http://localhost:8082
