server.port=8081
spring.application.name=customer-service

spring.datasource.url=jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jackson.serialization.indent-output=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.retail.common.DomainEventMessage
spring.kafka.consumer.properties.spring.json.trusted.packages=com.retail.common
retail.events.publishing.enabled=true
retail.events.outbox.enabled=true
retail.events.topic=customer.events
retail.events.consumer.enabled=true
retail.events.consumer.group-id=customer-projections
retail.events.product-topic=product.events
retail.events.order-topic=order.events

product.service.url=http://localhost:8082
