langchain4j.ollama.chat-model.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
langchain4j.ollama.chat-model.model-name=${OLLAMA_MODEL_NAME:llama3.2:3b}
langchain4j.ollama.chat-model.timeout=PT600S
langchain4j.ollama.chat-model.temperature=0.0
langchain4j.ollama.chat-model.max-output-tokens=1024